const {chromium}=require(process.env.PLAYWRIGHT_PATH||'playwright');const fs=require('fs'),assert=require('assert/strict');
(async()=>{const b=await chromium.launch({channel:'chrome',headless:true});const ctx=await b.newContext();const p=await ctx.newPage();const report={};await p.goto('http://127.0.0.1:5173/?engine=wasm');
for(const format of ['gif','webp']){
 const bytes=[...fs.readFileSync(process.cwd()+'/.cache/samples/animated.'+format)];
 const checks=await p.evaluate(async({bytes,format})=>{const {decode}=await import('/src/decode.ts');const runs=[];for(let i=0;i<3;i++){const d=await decode(new File([new Uint8Array(bytes)],'animated.'+format),new AbortController().signal);const c=document.createElement('canvas');c.width=d.bitmap.width;c.height=d.bitmap.height;const x=c.getContext('2d');x.drawImage(d.bitmap,0,0);runs.push([...x.getImageData(0,0,1,1).data]);d.bitmap.close();await new Promise(r=>setTimeout(r,137));}return runs;},{bytes,format});assert.ok(checks.every(c=>c[0]>240&&c[2]<20));report[format+'FirstFrame']=checks;
}
const orientation=await p.evaluate(async bytes=>{const {decode}=await import('/src/decode.ts');const d=await decode(new File([new Uint8Array(bytes)],'o.jpg'),new AbortController().signal);const c=document.createElement('canvas');c.width=d.bitmap.width;c.height=d.bitmap.height;c.getContext('2d').drawImage(d.bitmap,0,0);const result={width:c.width,height:c.height,corner:[...c.getContext('2d').getImageData(0,0,1,1).data]};d.bitmap.close();return result;},[...fs.readFileSync(process.cwd()+'/.cache/samples/orientation.jpeg')]);report.orientation=orientation;
// Model download failure then retry on same UI, with no cached model.
await p.route('**/models/**',r=>r.abort());await p.locator('#file').setInputFiles(process.cwd()+'/.cache/samples/format.png');await p.waitForFunction(()=>document.querySelector('#status').classList.contains('error'));assert.match(await p.locator('#status').innerText(),/내려받지/);await p.unroute('**/models/**');await p.getByRole('button',{name:'다시 시도',exact:true}).click();await p.waitForFunction(()=>document.querySelector('#status').textContent.startsWith('완료'),null,{timeout:120000});report.downloadRecovery=true;
await b.close();
// Cache-write failure inside the worker must still permit actual inference.
const b2=await chromium.launch({channel:'chrome',headless:true});const c2=await b2.newContext();await c2.route('**/assets/inference.worker-*.js',async r=>{const response=await r.fetch();await r.fulfill({response,body:'Cache.prototype.put = async function(){throw new DOMException("denied","QuotaExceededError")};\n'+await response.text()});});const p2=await c2.newPage();await p2.goto('http://127.0.0.1:4173/?engine=wasm');await p2.locator('#file').setInputFiles(process.cwd()+'/.cache/samples/format.png');await p2.waitForFunction(()=>document.querySelector('#status').textContent.startsWith('완료'),null,{timeout:120000});report.cacheDeniedWorks=true;await b2.close();fs.writeFileSync(process.cwd()+'/test-results/edgecases.json',JSON.stringify(report,null,2));console.log(report);
})().catch(e=>{console.error(e);process.exit(1)});
